repos:
  - repo: local
    hooks:
      - id: api-hooks
        name: API Hooks
        stages: [commit]
        always_run: true
        pass_filenames: false
        entry: pre-commit run
        language: system
        files: ^api/
        args: [--config, api/.pre-commit-config.yaml]

      - id: ui-hooks
        name: UI Hooks
        stages: [commit]
        always_run: true
        pass_filenames: false
        entry: pre-commit run
        language: system
        files: ^ui/
        args: [--config, ui/.pre-commit-config.yaml]
