# todo: add generating this file to ada cli.
steps:
  # todo: time the diff between kaniko and docker
  - name: "gcr.io/kaniko-project/executor:latest"
    id: "build-ui"
    waitFor: ["-"]
    args:
      - --destination=us-central1-docker.pkg.dev/rad-containers-hmed/cloud-canvas/ui:$SHORT_SHA
      - --cache=true
      - --cache-ttl=10h
      - --context=dir://./ui
