services:
  auth-database:
    image: pgvector/pgvector:pg16
    ports:
      - 6432:5432
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd

  auth-service:
    image: us-central1-docker.pkg.dev/rad-containers-hmed/shared/auth-service:latest
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_SERVER=auth-database
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      - LOCAL_DB=true
    depends_on:
      - auth-database

  database:
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=canvasdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd

  api:
    build:
      dockerfile: ./Dockerfile
      context: ./api
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/var/config/gcloud/application_default_credentials.json
      - GITHUB_TOKEN=$GITHUB_TOKEN
    ports:
      - 8000:8000
    volumes:
      - ~/.config/gcloud:/var/config/gcloud

  ui:
    build:
      dockerfile: ./Dockerfile
      context: ./ui
    ports:
      - 3000:80
    volumes:
      - ./ui/src:/app/src
      - ./ui/public:/app/public
      - ui_node_modules:/app/node_modules
    environment:
      - REACT_APP_ENV=production

  provisioner-deploy:
    platform: linux/amd64
    build:
      dockerfile: ./Dockerfile
      context: ./provisioner
    # environment:
    #   - GOOGLE_APPLICATION_CREDENTIALS=/var/config/gcloud/application_default_credentials.json
    #   - GITHUB_TOKEN=$GITHUB_TOKEN
    ports:
      - 8000:8000

  api-deploy:
    platform: linux/amd64
    build:
      dockerfile: ./Dockerfile
      context: ./api
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/var/config/gcloud/application_default_credentials.json
      - GITHUB_TOKEN=$GITHUB_TOKEN
    ports:
      - 8000:8000
    volumes:
      - ~/.config/gcloud:/var/config/gcloud

  ui-deploy:
    platform: linux/amd64
    build:
      dockerfile: ./Dockerfile
      context: ./ui
    ports:
      - 3000:80
    volumes:
      - ./ui/src:/app/src
      - ./ui/public:/app/public
      - ui_deploy_node_modules:/app/node_modules
    environment:
      - REACT_APP_ENV=production

volumes:
  ui_node_modules:
  ui_deploy_node_modules:
