apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: app-api@rad-dev-canvas-kwm6.iam.gserviceaccount.com
automountServiceAccountToken: true
