apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: googlesm
spec:
  provider:
    gcpsm:
      projectID: rad-dev-canvas-kwm6
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: cluster-0
          clusterProjectID: rad-dev-canvas-kwm6
          # using the same as the app, because when the new secrets feature works, we can delete this
          serviceAccountRef:
            name: api
            namespace: default
