apiVersion: v1
kind: Service
metadata:
  name: ui
  # annotations:
  #   cloud.google.com/neg: '{"ingress": true, "exposed_ports": {"8080":{}}}'
spec:
  selector:
    app: ui
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
