apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      serviceAccountName: api
      containers:
        - name: ubuntu
          image: us-central1-docker.pkg.dev/rad-containers-hmed/shared/ubuntu:latest
          imagePullPolicy: Always
          args: ["tail", "-f", "/dev/null"]
