apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
  namespace: default
spec:
  selector:
    app: ubuntu
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
